### ISSUE TITLE
Renderer Process Crashed

### ISSUE THREAD

**Issue by HelpfulBugTester** [tagspaces/tagspaces#940] opened 2019-03-27 11:57 UTC
**Describe the bug**
Application crashes resulting in the "Renderer Process Crashed" dialog being displayed.

**To Reproduce**
Location View Type: Grid View
-Select Files(Files are of image type "jpg")
-Tag using Ctrl+Click on tag or 'Tag selected entries' button Add/Remove(either operation)

*Program appears stalled for unspecified time, but renaming process is active.
"Renaming Successfully..." caption is shown.
Navigation is locked during this time*

"Renderer Process Crashed" dialog shown

**Expected behavior**
Smooth transition from tagging of files to continuation of operation.

**Screenshots**
![render_process_crashed_x64-3 1 1_portable](https://user-images.githubusercontent.com/48983390/55074159-ec6d0f00-5065-11e9-936c-1e363cee6256.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 3.1.1 x64 portable

**Additional context**
Tagging operation completes, but continuation of operation is not successful 100% of the time.

Example:
Memory Usage thru task manager is approx. 255.7 MB at application startup 
				" 						  367.4 MB upon entry to folder with 154 images 
				" 						  1756 MB at time of "renaming successfully" shown 
				" 						  3959 MB at the time of crash
				
My observation:
Single instances or even multiple instances of tagging can be completed successfully however, when a certain threshold of memory usage is reached by the application, the crash occurs.

**Comment by uggrock** [comment] 2019-08-12 16:00
Closing since not reproducible.

**Closed by uggrock** 2019-08-12 16:00 UTC
