### ISSUE TITLE
scrollbar for file is undragable

### ISSUE THREAD

**Issue by kbrannen** [tagspaces/tagspaces#1938] opened 2023-06-22 18:02 UTC
**Describe the bug**
When a file is selected and the text is longer than a page, there is a scrollbar, but it is not possible to grab the scrollbar and use it. In my case it's an html file, although a quick check shows the same problem on txt files also.

**To Reproduce**
1. Find and select a longer text or html file.
2. See the scrollbar on the right of the text area.
3. Try to grab the scrollbar to scroll down the page ... I can't.

**Expected behavior**
To be able to grab the scrollbar and scroll down the page.

**Desktop Application:**
 - Operating System: Linux, Ubuntu 22.04
 - TagSpaces Version: noticed on 5.3.2; upgraded to 5.3.5 and the problem is still there

**Comment by kbrannen** [comment] 2023-06-22 22:45
I don't know that "undragable" is the correct term, but whatever. I should also point out that when you move the mouse over the control of the scrollbar, the control actually disappears, hence why I said "ungrabbable". But I won't quibble over the term as long as we can get that fixed. :)

**Comment by uggrock** [comment] 2023-06-23 11:49
Never mind, the issue is fixed in version 5.4.0, which we just released.

**Comment by uggrock** [comment] 2023-06-23 11:49
Thanks for reporting!

**Closed by uggrock** 2023-06-23 11:49 UTC
