### ISSUE TITLE
Mass-Tagging has no effect

### ISSUE THREAD

**Issue by julianseeger** [tagspaces/tagspaces#658] opened 2018-01-08 08:50 UTC
how to reproduce:
- do a search (in subfolders) with multiple results
- select multiple results (>=2)
- tag them (using ctrl+t or the yellow context menu)

expected behavior:
- files should be tagged

actual behavior:
- files show up tagged in the current search result but are not actually tagged (as soon as I repeat the search or open a containing folder for one of the files, no tags show up for the files)

I'm using TagSpaces 2.9.0.20170715161933 (Pro with Sidecar-Files) on Windows 10.

**Comment by uggrock** [comment] 2018-02-04 13:39
We are not able to reproduce this issue under Linux.... We will try ti reproduce it under Windows soon.

**Comment by 90ender** [comment] 2018-05-21 03:47
I can verify that selecting multiple file and selecting 'add / remove tag' from the right click context menu in the file list and grid view panes, only applies the tags to the file right clicked on.

**Comment by uggrock** [comment] 2018-05-21 07:01
You have to use the Add/Remove Tags menu item from the perspective menu, which can be opened from the round yellow button in the bottom right part of the screen.
![screenshot from 2018-05-21 09-00-46](https://user-images.githubusercontent.com/1249777/40294352-7df2fd66-5cd5-11e8-94c8-7613893bc461.png)

**Comment by julianseeger** [comment] 2018-05-21 16:28
Well, the issue still exists on Windows but you need to use the search functionality to reproduce it.
Right click doesn't work anyways because that deselects every file except the one right clicked on. So I'm using the round yellow bubble (as described).

Search, klick "Show subfolders content", select 2 or more files, click on the yellow round bubble, "Add / Remove Tags" (as shown in your screenshot) and then add a tag. Clear the search, repeat the search and no tags are applied at all.

I'm not using tagspaces on ubuntu so I cannot test if it happens there too.

**Comment by uggrock** [comment] 2019-02-02 10:58
this issue is fixed in version 3.0.x

**Closed by uggrock** 2019-02-02 10:58 UTC
