### ISSUE TITLE
Android: Filtering for a tag breaks sorting

### ISSUE THREAD

**Issue by EXCIDIVM** [tagspaces/tagspaces#1866] opened 2023-02-12 14:58 UTC
**Describe the bug**
Android app. When using the "show files with this tag" option, sorting no longer works. No matter which sort option (by title, by date etc.) is selected, it will be ignored entirely.

**To Reproduce**
1. Go to Tag Library
2. Click on any tag and select "Show Files With This Tag"
3. Select any sort option (e.g. by First Tag)
4. Nothing will be sorted

**Expected behavior**
Files will be sorted as specified.

**Screenshots**

**Desktop Application:**
 - Operating System: Android 12
 - TagSpaces Version 5.2.4

**Comment by sytolk** [comment] 2023-02-13 07:36
possible duplicate of this: https://github.com/tagspaces/tagspaces/issues/1864#issuecomment-1427463618

@EXCIDIVM can you try other sorting options by size ?

**Comment by EXCIDIVM** [comment] 2023-02-13 14:56
> possible duplicate of this: [#1864 (comment)](https://github.com/tagspaces/tagspaces/issues/1864#issuecomment-1427463618)
> 
> @EXCIDIVM can you try other sorting options by size ?

To clarify: After using a filter, none of the six sorting options do anything (title, size, date etc.).

**Comment by uggrock** [comment] 2023-02-17 12:09
Fixed in v5.2.5 -> closing

**Closed by uggrock** 2023-02-17 12:09 UTC
