### ISSUE TITLE
NTFS compressed files don't show tags

### ISSUE THREAD

**Issue by jirkacapek123** [tagspaces/tagspaces#2157] opened 2024-08-25 10:39 UTC
**Describe the bug**
Any file which has NTFS file compression enabled just doesn't show up when I search for a file by tag. I have also appended a screenshot which I hope will be helpful.

**To Reproduce**
1. tag any NTFS compressed file
2. now try to find it by search with tag

**Expected behavior**
I expected to have my files show up when searching by tag, but every NTFS compressed file just doesn't show in the search at all.

**Screenshots**
![Screenshot 2024-08-25 123113](https://github.com/user-attachments/assets/b44de8b7-65ef-4ccc-bc69-082fb345f9bd)

**Desktop Application:**
 - Windows 11 build 26100
 - TagSpaces v5.9.2

**Comment by sytolk** [comment] 2024-08-26 09:19
@jirkacapek123 can you check if in you location index file exist? "ISO Images"/.ts/tsi.json 
and can you publish it (if it's not too big). Thanks!

**Comment by jirkacapek123** [comment] 2024-08-26 09:54
Yes, the file is in the folder, and I have included it.
[tsi.json](https://github.com/user-attachments/files/16747101/tsi.json)

**Comment by sytolk** [comment] 2024-08-26 10:10
Can you show me what ISO file have Win11 tag? I have see tags: [] empty in all you iso files in Locations. Can you check date created of this tsi.json ? If you force recreation of tsi.json is this help to find the files by tag `Win11` ? 
![Screenshot 2024-08-26 at 13 09 31](https://github.com/user-attachments/assets/822e3dbd-e0bb-4ed9-bbbc-2b6f38d7c2dd)

**Comment by sytolk** [comment] 2024-08-26 11:37
Maybe this is not connected with NTFS compressed file. It's appears like duplicate of https://github.com/tagspaces/tagspaces/issues/2148  this is already fixed in develop.

**Comment by sytolk** [comment] 2024-08-27 06:05
@jirkacapek123 you can check if v5.10.1 fix this issue: https://github.com/tagspaces/tagspaces/releases/tag/v5.10.1

**Comment by jirkacapek123** [comment] 2024-08-27 06:07
Yes, I will check as soon as I get to my computer.

**Comment by jirkacapek123** [comment] 2024-08-28 11:38
I tried it and it appears that it was fixed, the tags show up instantly now.

**Closed** 2024-09-02 14:28 UTC
