### ISSUE TITLE
Program wan't start on mac os x catalina

### ISSUE THREAD

**Issue by gitalexa** [tagspaces/tagspaces#1022] opened 2019-09-09 11:02 UTC
**Describe the bug**
Program wan't start on mac os x catalina. A Window appears: "Das Programm „TagSpaces“ kann nicht geöffnet werden." The Program TagSpaces can not be opened

**To Reproduce**
download it
unzip it
double click it...

**Desktop (please complete the following information):**
 - macOS 10.15 (19A546d)

**Comment by uggrock** [comment] 2019-10-15 10:42
The issue is caused probably by this one: https://github.com/electron-userland/electron-builder/issues/4299

**Comment by uggrock** [comment] 2019-10-21 14:58
fixed in version 3.2.6

**Closed** 2019-10-21 14:58 UTC
