### ISSUE TITLE
New tags have "undefined" in the name

### ISSUE THREAD

**Issue by FTWilliams** [tagspaces/tagspaces#430] opened 2016-04-12 20:10 UTC
First time user, running a Windows machine (Lenovo laptop) using Windows 8.1.
I just installed Tagspaces and went to organize an image folder (.jpgs and .pngs). I created some tags, selected about 100 images and choose "tag selected files."

As soon as I did I started getting a series of Alert messages saying "Renaming [filename] failed."

A few minutes later I went to my folder and every image had been deleted (they were there -without question- before I ran Tagspaces). I went back to the Tagspaces viewing pane and every image that I had tagged was still listed but it wouldn't display the image, instead the displaying the default .jpeg image showing it failed to load. 

In the file folder itself all the images are there, but they have new filenames: "[Original Filename]"undefined"[tag]"undefined"[tag]"undefined..." (the last bit repeats a few times). I can't rename the files or view their properties.

Thankfully, these are not one-of-a-kind, high-importance images, but I'd still like to recover them and find out why Tagspaces did this. The only thing I can really think of is that the tag included some dashes ("-"), but those weren't flagged by the program and are perfectly acceptable in a windows filename.

**Comment by FTWilliams** [comment] 2016-04-12 20:12
Update: I tried to tag a few more files the same way to see if I could catch anything I missed and it worked fine. The tags have been applied correctly (for the first batch the tags don't look to be completely correct; I colored them red, but they're showing the default green).

All the same, definitely not going to use this on any important files, at least until I'm *certain* I know what went wrong and how to avoid it.

**Comment by mladensap** [comment] 2016-04-13 08:43
Hello, 
could you tell us exactly which version of the program you use, to try to reproduce the error?
Thanks in advance.

**Comment by FTWilliams** [comment] 2016-04-13 11:03
It's version 2.2.1. (I just installed it yesterday).

**Comment by mladensap** [comment] 2016-04-13 11:22
32 bit or 64 bit?

**Comment by FTWilliams** [comment] 2016-04-13 15:56
64 bit.

**Comment by jeanbaptisteC** [comment] 2016-04-19 12:56
Dear all,

I have just downloaded and started your program which seems very promising,

I run 2.2.1 version with lubuntu 12.04 32 bits, and I got the issue that is mentioned here. Each new files tagged as an undefined added, when I try to show files with this tag, nothing shows up.

Thank you,

**Comment by abruenin** [comment] 2016-04-29 13:37
Same problem with Windows, tried with several, now on 2.2.5. 32 bit works, 64bit messes up the tags with 'untitled'.

**Comment by roxfanuk** [comment] 2016-05-03 21:08
Linux Mint 17.3 with 64-bit TagSpaces 2.3.0 - BuildID: 2.3.0.20160429112036

Same problem, my guess is that the 64 bit version is missing the comma seperator for the tags - where it should be, the word "undefined" gets written instead.

**Comment by viktor-c** [comment] 2016-06-29 13:19
Hi friends! 
Using Linux Mint 18 Beta and 
TagSpaces 2.4.0 - BuildID: 2.4.0.20160609091902

Problem is when adding one or multiple built-in tags, imported or newly create tags to a file, undefined appears.
Hope this gets a fix soon :)

**Comment by Buena-Vista** [comment] 2016-08-23 00:09
newly installed v2.4.0 got the same "undefined" error when tagging with or without a pre-existing tag.  restarted the program (running in portable mode), now it works.  quite bizarre.  maybe it was because I changed options during that first execution and didn't restart?

but now.....
no space between the title and [tags] even on fairly short names.  the docs say a space should exist and I'd prefer that.

I'm actually teaching myself nw.js right now.  I look forward to maybe helping out some day, altho I'm a slow learner.  This looks like a great tool.  Best wishes for continued success.

**Comment by uggrock** [comment] 2016-10-12 08:17
I will close this issue since, there are no reports for reproducing it with 2.5.0

**Comment by Lanzafame** [comment] 2016-10-31 05:33
Running version 2.5.0 - BuildID: 2.5.0.20160905130746a on Fedora 25 64bit. Attempted to add two tags to a batch of pdf's and they were renamed with undefined at the end of the filename and then undefined after each tag I had applied.

**Comment by nmarshall23** [comment] 2016-11-09 10:37
Running version 2.5.0 - BuildID: 2.5.0.20160905130746 on Ubuntu 14.04.5.

Trying to add a tag, say named `TagName` add `TagNameundefined` is added as a tag. When I try to remove the tag, it now has a `undefinedundefined` tag. Trying to remove that tag I get 'undefinedundefinedundefined`.

**Comment by roxfanuk** [comment] 2016-12-12 19:10
I should add that my issue resolved itself after uninstalling, then (attempting) installing 32bit version, then reinstalling 64bit.
After that it was fine. No idea how, but maybe worth some experimentation if anyone has the energy.

**Comment by BotChen** [comment] 2017-01-21 07:43
Same issue for me running version 2.6.0 on 32bit Windows 10. 
![undefined](https://cloud.githubusercontent.com/assets/23055059/22172988/49ec35ae-dff0-11e6-9f23-85295f920ce1.PNG)

**Comment by uggrock** [comment] 2017-01-21 17:03
Issue is preliminary fixed in version 2.6.4. An improved fix will follow in version 2.7

**Closed by uggrock** 2017-01-21 17:03 UTC
