### ISSUE TITLE
Android App: can't type on Cyrilic

### ISSUE THREAD

**Issue by snakth** [tagspaces/tagspaces#216] opened 2015-02-22 21:08 UTC
Create HTML file.
When trying to input text on Russian via keyboard nothing happens (literally nothing).
When copy/paste Cyrillic letters it's working.
Typing Latin is also working.

Sony Xperia z2
Android 4.4.4.

**Comment by mladensap** [comment] 2015-02-24 20:20
It is reproducible also on Nexus5 with Android 5

**Comment by tbleiker** [comment] 2015-03-10 09:59
The same happens for characters like "ö", "ä" and "ü" with a (Swiss)German keyboard on a LG G Pad (Android 4.4.4).

**Comment by allyalla** [comment] 2015-04-16 17:03
UTF 8 bug. Who uses limited ANSI components instead in any editors? Or its a special app for 'the default country usage' only?
Also cyrilic, english, numeric symbols ie any... cant be typed into the paths selection dialogs (but when you pasting them from the clipboard - all path appears well in the path textboxes ). WTF?

**Comment by tbleiker** [comment] 2015-05-18 12:50
Any progress? Do you develop with Eclipse? I just came across [this](http://stackoverflow.com/a/11548775) on stackoverflow.

**Comment by uggrock** [comment] 2015-05-19 08:56
Yes the issue is already solved and will be released this or the next week.

**Comment by tbleiker** [comment] 2015-05-19 09:02
You're awesome Ilian! :smile: Thank you very much (once again) for all the effort you put into this project! Looking forward to the next release!

**Comment by uggrock** [comment] 2015-06-07 15:16
fixed in 1.11.3 release from today

**Closed** 2015-06-07 15:17 UTC
Labels: android
