### ISSUE TITLE
TAGSearch not working - version 3.0 pro

### ISSUE THREAD

**Issue by JerzyPa** [tagspaces/tagspaces#818] opened 2019-01-01 12:55 UTC
Tag search in version 3.0 pro Windows delivers no hints.

**Comment by uggrock** [comment] 2019-01-01 13:11
I am not able to reproduce this issue. Can you share some details about how we can reproduce it? BTW search is only working when you have an opened location.

**Comment by uggrock** [comment] 2020-12-04 23:10
this issue should be fixed meanwhile -> closing

**Closed by uggrock** 2020-12-04 23:10 UTC
