### ISSUE TITLE
Rename file fails silently

### ISSUE THREAD

**Issue by svantesalen** [tagspaces/tagspaces#1171] opened 2020-08-14 08:17 UTC
**Describe the bug**
I tried to rename a file using tagspaces. The file name was not changed. No message from tagspaces.

**To Reproduce**

1. Start tagspace.
2. Select the Documents folder. 
3. Selected a pdf file.
4. Right-click on the file and choose "rename" from the pop-up. 
5. Renamed the file and click "ok". 

My result: the pop-up dissapeared, but the file was not renamed; not in tagspaces window and not on disk.

**Expected behavior**
I expected the file to be renamed or an error message.

**Screenshots**
-
**Desktop Application:**
 - Operating System: windows 10 pro, version 1909, build 18363.959

 - TagSpaces Version 3.5.4

**Additional context**
I made sure that the file was not open. 
I tried files I had not opened since last restart. 
I tried pdf and docx extensions.

**Comment by sotto** [comment] 2020-08-26 13:00
Not sure if this is helpfull, but I'm unable to reproduce (windows 10, TS desktop 3.5.4): file renamed succesfully here (i'm just another enduser)

**Comment by uggrock** [comment] 2020-09-06 08:45
hmm, interesting I am also not able to reproduce the issue on 3.6.1 version, so I am going to close it. Please reopen if you experience it again.

**Closed by uggrock** 2020-09-06 08:45 UTC
