### ISSUE TITLE
"Create tag group" multiplied by amount of tag groups

### ISSUE THREAD

**Issue by dantveita** [tagspaces/tagspaces#367] opened 2015-12-21 15:08 UTC
Whenever i create a new tag-group, the new created group is multiplied by the number of previous tag-groups. So say i have three groups. When i create a fourth group, i get x3 of that group created.

**Comment by uggrock** [comment] 2015-12-21 15:21
I was not able to reproduce the issue, can you give us some more information like the version, the platform and steps for the reproduction?

**Comment by dantveita** [comment] 2015-12-21 15:49
Tagspaces version 2.0.4 on OSX 10.11.2 (64bit)

Heres a link to a gif reproducing the bug.
http://g.recordit.co/wnZOQTMnsI.gif

**Comment by uggrock** [comment] 2015-12-22 18:31
Thank you for the video!

**Comment by elemakil** [comment] 2016-01-07 13:41
I can confirm this bug on Xubuntu 15.04 and OSX 10.11.2 (64 bit) with Tagspaces 2.0.4

**Comment by uggrock** [comment] 2016-01-12 08:52
Fixed in the next release

**Closed by uggrock** 2016-01-12 08:52 UTC

**Comment by uggrock** [comment] 2016-01-28 12:17
fix in 2.1.0
