### ISSUE TITLE
screen freeze on viewing odt file

### ISSUE THREAD

**Issue by stefan38** [tagspaces/tagspaces#514] opened 2016-11-28 17:44 UTC
I am using Ubuntu Mate 16.10. I saved an article in ODT format. It contains an image, text with Unicode characters and a link. It can be opened, viewed and edited in LibreOffice Writer. On previewing in Taggspaces it displays only the title of the document, the image and the link without the article's text content. The real problem appears when the screen freezes and only restart helps. I tried to preview an other ODT file with similar content and Taggspaces displayed it correctly without freezing.

**Comment by uggrock** [comment] 2016-12-12 12:33
this is probably an issue with the used library (webodf.js) for the rendering of ODF documents. I will close the issue since it is probably hard reproduce and fix.

**Closed by uggrock** 2016-12-12 12:33 UTC
