### ISSUE TITLE
Blank window following install

### ISSUE THREAD

**Issue by J-Garnett** [tagspaces/tagspaces#1388] opened 2021-04-17 06:29 UTC
I just downloaded and installed the lite version (tagspaces-win-3.9.5.exe).

When I open it up, the window flashes the icon in colour in the centre of the window, on a grey background, then goes entirely white. It also tries to correct to the internet, however, whether I let through my firewall or not the same thing happens. 
I have a title bar that reads TagSpaces Desktop, but there is absolutely nothing else in the window.

My system exceeds the Windows system requirements. Windows 10 x64, Though I regularly use a 2560x1440 resolution, this has no observed impact on the software. In Process Explorer, there is 1 primary process, and 4 sub processes. Their numbers do change when I open the TagSpaces window, but their is no significant impact on the TagSpaces window, itself.

![Annotation 2021-04-17 155829](https://user-images.githubusercontent.com/7764406/115104178-e53f3380-9f95-11eb-87f8-1687d847c34b.jpg)

**Comment by uggrock** [comment] 2021-04-18 07:17
Did you have used previous version of TagSpaces on this computer? And if yes, which version or long ago roughly?

**Comment by uggrock** [comment] 2021-06-16 04:22
closing since issue is not reproducible

**Closed by uggrock** 2021-06-16 04:22 UTC
