### ISSUE TITLE
Cant see any thumbnail in any persoective (Android)

### ISSUE THREAD

**Issue by allyalla** [tagspaces/tagspaces#387] opened 2016-02-04 00:28 UTC
Hello. 
Is there no any view that is able to show small thumbnails along with the file names right now at all on Android ? Is it normal behaviour for last release?

**Comment by alkamen** [comment] 2016-02-08 13:39
No thumbnail, no mp3 audio.

**Comment by allyalla** [comment] 2016-03-14 23:05
The month to these stupid issue. It even wasnt "recognised" as the bug... Hello? People are you frozen there? It seems that this stupid program with it's project along will never file Android version. Because of the stupid author or watsoever who is "in charge" who just cant program normally without allowing newer and newer stupid issues (which stay totally unsolved even if they have been reported properly directly in here). Why than just not to barry your full of bugs uggly pice of crap, tell sorry to normal people for wqsting their time for your crap and go to do something more simplem, that you really able to do? Instead of making some stupid "updates", which contain even more bugs than previous versions. Just one word - its Stupidity.

**Comment by uggrock** [comment] 2016-03-23 16:11
The issue is fixed in the 2.1.4 release.

**Closed by uggrock** 2016-03-23 16:11 UTC

**Comment by allyalla** [comment] 2016-03-23 17:12
Awesome speed of fixing too obvious Super-bug (from the very first testing and launching of the app) (It was making completly no sence of using whole app). I thought it will be hanging unsolved in queue for next five years in here. Thus, it would totally barried these app (as for me). But now I see - I was really wrong. The bug was solved very quickly. Thanks, and sorry if I was too rude, I was trying to point on the degree of that bug importance.
