### ISSUE TITLE
Refresh Issue after adding tags

### ISSUE THREAD

**Issue by RevitArkitek** [tagspaces/tagspaces#1371] opened 2021-03-28 14:19 UTC
When I select multiple files and add a tag, only the first file shows the newly added tag.  If I go to the parent directory and back down, then all files show the tag that was added.  Seems to be a refresh issue. 
V3.8.4

**Comment by alnumac** [comment] 2021-04-10 17:54
I also have this issue with version 3.9.5. I noticed that if I add a tag without selecting the file first (such as dragging a tag from the tag library), the tag does not appear without refreshing the directory.

**Comment by uggrock** [comment] 2021-04-12 07:40
I am not able to reproduce the issue on Linux, which tagging method are you using (file renaming or sidecar files)?

**Comment by RevitArkitek** [comment] 2021-04-12 12:54
I'm using sidecar files.  Windows 10

**Comment by alnumac** [comment] 2021-04-12 14:08
Same here.

Mathieu A. Cormier

**Comment by uggrock** [comment] 2021-07-15 21:24
could not be reproduced, it is probably fixed in one of the latest version, please reopen if the problem persists.

**Comment by RevitArkitek** [comment] 2021-07-20 12:10
I'm using v3.10.4 and the issue is still present.

**Comment by sytolk** [comment] 2021-07-26 12:35
@RevitArkitek can you attach screenshot after DnD tag on multiple selected files. Maybe the issue is with tag is it starting with Uppercase ?

**Comment by mladensap** [comment] 2021-07-26 12:36
I can't reproduce the issue. v3.10.4 / windows 10

**Comment by RevitArkitek** [comment] 2021-08-02 00:06
It still doesn't add the tags even if it starts with lower case.  I'm not sure what a screenshot would show so I took a video:  https://michael-coffey.tinytake.com/msc/NTY3ODU5MV8xNzU3NzcwNw

**Comment by sytolk** [comment] 2021-08-02 05:19
@RevitArkitek thanks for the video! 
How deep is your "Deep space 9" folder? I cant see it in "Star Trek" location.
Can I have your relative path of the "Deep space 9" from "Star Trek" location ? maybe the use is related with path

**Comment by sytolk** [comment] 2021-08-02 05:23
I have repeat this issue thanks!

**Comment by RevitArkitek** [comment] 2021-08-02 13:23
Star Trek/Models/Deep Space 9
Thanks for your efforts!

**Closed** 2021-11-15 06:53 UTC
