### ISSUE TITLE
Cannot copy S3 files with umlauten

### ISSUE THREAD

**Issue by SpiGAndromeda** [tagspaces/tagspaces#1237] opened 2020-11-08 03:25 UTC
I tried to copy a bunch of files in an S3 bucket from one location to another. All files are working fine expect the ones with umlauten. TagSpaces simply shows an "Copying files failed" error.

**Desktop Application:**
 - Operating System: macOS 10.15.7
 - TagSpaces Version 3.6.2

**Comment by uggrock** [comment] 2021-07-13 09:33
could not reproduce this in version 3.10.4 -> closing

**Closed by uggrock** 2021-07-13 09:33 UTC
