### ISSUE TITLE
erratic behavior when adding notes

### ISSUE THREAD

**Issue by KIRINPUTRA** [tagspaces/tagspaces#635] opened 2017-09-10 12:32 UTC
Pro user here on a Macbook Air with Mavericks.

I've added files w/i Tagspaces using the +NEW button. The workflow is generally very clunky, forcing a lot of use of the mouse — but I'm kind of willing to help Tagspaces evolve, since there's nothing else like it out there. However, Tagspaces is losing my info in at least two ways:

1 — A .txt file created w/i Tagspaces a day ago can no longer be opened w/i Tagspaces, nor opened natively from w/i Tagspaces. (I can open it via OSX Finder. However, I can't find it via tags there since the tags are w/i Tagspaces.) Any attempt yields this error: "Alert ... Loading [filename] failed." I notice that w/i Tagspaces, the filename is missing the ".txt" suffix. In Finder, though, the suffix is showing. In Tagspaces, the tags for the file are not showing. However, I found the file using a tag search, and the sidecar file is right where it should be.

2 — An .html file created w/i Tagspaces four days ago is just blank now. I'm 80% sure I had saved it before leaving Tagspaces that day.

Assistance or advice urgently requested.

**Comment by KIRINPUTRA** [comment] 2017-09-11 02:06
Update on this problem. Following a tag search, many files that show up will appear tagless, and can't be opened either w/i Tagspaces or natively from w/i Tagspaces. This doesn't happen with non-tag search or browsing.

**Comment by uggrock** [comment] 2017-09-11 15:39
We could not reproduce the described issue, can you specify which version of the application you are using?

**Comment by KIRINPUTRA** [comment] 2017-09-11 16:29
I'm using Pro 2.9.0 (for Mac).

**Comment by KIRINPUTRA** [comment] 2017-09-11 16:30
I wonder if it has something to do with spaces or non-Western characters in filenames. Sometimes I'm able to fix things by renaming the file (outside Tagspaces), other times not.

**Comment by uggrock** [comment] 2020-12-04 23:18
issue is obsolete for > v3 -> closing

**Closed by uggrock** 2020-12-04 23:18 UTC
