### ISSUE TITLE
pro-3.2.5: cannot search (sidecars)

### ISSUE THREAD

**Issue by jhsysphr** [tagspaces/tagspaces#1031] opened 2019-10-13 01:58 UTC
**Describe the bug**
Using sidecars for tags.
Cannot search by folder/filename or tags.

**To Reproduce**
1. Go to search, type in anything in folder/file name. press search.

expected results: list of folders/files containing search string
actual results: no results.

2. Go to search, select a search tag in "at least" section (confirmed that at least 1 folder has the tag). press search.

expected results: folder with the tag
actual results: no results.

3. In options, make sure tag is stored by side cars
Make sure no file has the tag assigned.  But at least one file/folder has the tag string in filename with square brackets.
Go to search, select a tag which was never used.

expected results: no results. Because using sidecars.
actual results: the file which the in-name tag appeared.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version pro-3.2.5

**additional info**
- all default locations removed. only custom locations are used
- running in portable mode

**Comment by uggrock** [comment] 2019-10-15 10:41
We were not able to reproduce this, but we are still investigating on it.

**Comment by uggrock** [comment] 2019-10-15 10:41
https://github.com/electron-userland/electron-builder/issues/4299

**Comment by uggrock** [comment] 2022-12-15 16:34
Not reproducible anymore -> closing

**Closed by uggrock** 2022-12-15 16:34 UTC
