### ISSUE TITLE
New tags have "undefined" all over the place

### ISSUE THREAD

**Issue by jannepeltola** [tagspaces/tagspaces#405] opened 2016-03-07 02:11 UTC
I'm running OS X 64-bit version 2.1.1.

My version of TagSpaces seems to have an issue somewhere that drops "undefineds" all over the place when creating new tags.

Steps to reproduce:

I open a directory with a PDF file in it:
![File before](https://dl.dropboxusercontent.com/u/6305285/2016-03-06_file_before.png)

The file shows up nicely in TagSpaces:
![Entry before](https://dl.dropboxusercontent.com/u/6305285/2016-03-06_entry_before.png)

I go ahead and tag it "foo", which is a new tag:
![Tag operation](https://dl.dropboxusercontent.com/u/6305285/2016-03-06_tag_operation.png)

Wild undefineds appear! 
![Entry after](https://dl.dropboxusercontent.com/u/6305285/2016-03-06_entry_after.png)

The undefineds are in the file name as well:
![File after](https://dl.dropboxusercontent.com/u/6305285/2016-03-06_file_after.png)

The only place where the undefineds don't show up is the tag list:
![Tag list](https://dl.dropboxusercontent.com/u/6305285/2016-03-06_tag_list.png)

**Comment by uggrock** [comment] 2016-03-10 08:44
We tried to reproduce this issue on different macs but without any success, can you please try to share with us some more details? Please try also to get a fresh copy of the application.

**Comment by jannepeltola** [comment] 2016-03-12 21:25
Thanks for looking into this!

I did some further testing and the 32-bit version seems to work fine. The issue only affects the 64-bit version. I'm running the pre-built binaries from the website, stable version 2.1.1, on OS X 10.10.5. Let me know if you need any further details or excerpts from log files.

I had a look at the underlying Javascript code and I couldn't see any obvious causes there. I suspect this is caused by the native wrapper rather than the app itself.

**Comment by adrianoprospero** [comment] 2016-03-14 22:55
I have the same problem, in both Linux Mint and Windows 10...

**Comment by uggrock** [comment] 2016-03-15 13:41
Hi,

we are still not able to reproduce this issue. Can somebody of you try the pre-release 2.1.2 from here https://github.com/tagspaces/tagspaces/releases/tag/v2.1.2 and report if the issue is still reproducible there. Thank you in advance for the support.

best regards,
Ilian

**Comment by uggrock** [comment] 2016-03-23 16:33
I am closing this issue, because I believe it is fixed in version 2.1.4.

**Closed by uggrock** 2016-03-23 16:33 UTC

**Comment by jeanbaptisteC** [comment] 2016-04-19 08:40
Dear all, 

I have just downloaded and started your program which seems very promising, 

I run 2.2.1 version with lubuntu 12.04 and I got the issue that is mentioned here. Each new files tagged as an undefined added, when I try to show files with this tag, nothing shows up. 

Thank you,

**Comment by uggrock** [comment] 2016-04-19 12:01
duplicate issue to #430
