### ISSUE TITLE
Tags are searchable when I manually type the tag, but aren't when I select "Show Files With This Tag" in the tag sidebar?

### ISSUE THREAD

**Issue by motreo** [tagspaces/tagspaces#1426] opened 2021-05-28 22:15 UTC
I only just started using TagSpaces and encountered this issue. When I manually search for a tag I can see a list of files with that tag attached to it. When I find the same tag in the tag sidebar and click on "Show Files With This Tag", however, no results are found.

**Comment by CarJem** [comment] 2021-06-09 00:53
Confirmed from TagSpaces 3.10.2 on Windows 10

**Comment by sytolk** [comment] 2021-06-10 13:31
I cannot repeat this issue on Windows 10 (Using Sidecar and Filename Tags). Can you attach a screenshot here after "Show File With This Tag" is pressed?

**Comment by CarJem** [comment] 2021-06-10 17:22
![image](https://user-images.githubusercontent.com/18092668/121569543-e7020200-c9ee-11eb-8598-c437396dbfe0.png)
![image](https://user-images.githubusercontent.com/18092668/121569584-f2552d80-c9ee-11eb-9614-2455eb60d3df.png)

**Comment by uggrock** [comment] 2021-06-10 17:36
@CarJem, thanks for the screenshots! I was able to reproduce the issue, the problem is the that tag has characters in uppercase. We are going to fix this for the next release.

**Comment by CarJem** [comment] 2021-06-10 17:37
Thanks guys!!! I'll be looking forward to it.

**Comment by uggrock** [comment] 2021-06-16 04:21
fixed in 3.10.4

**Closed by uggrock** 2021-06-16 04:21 UTC
