### ISSUE TITLE
picture preview flickers a lot  &  please select the current image on the list

### ISSUE THREAD

**Issue by lezzlee** [tagspaces/tagspaces#202] opened 2015-02-02 16:39 UTC
Preview area flickers everytime I drop a tag or step the image (top right < >) or double-click (select) another one from the list.

Also would be great that the current image is selected on the list. It would ease dropping tags after stepping the image with the top right < > buttons.

Thank you,
L

**Comment by uggrock** [comment] 2015-02-02 21:15
You can drop tags in tag area of the opened image.
Selecting the currently opened file, is difficult because the user can change the folder, and then there will be nothing to select.
The flickering comes from the fact that on every added tags the files is renamed and should be reloaded to reflect the changes.

**Comment by uggrock** [comment] 2015-02-02 21:17
There is an optimization potential for the flickering although, that's why I am not closing the issue.

**Comment by internetimagery** [comment] 2016-12-12 11:01
This is a minor itch I'd love to see scratched also. I tag a lot of images that have been optimized, making the preview take just that tiny bit longer. Every tag addition causes the app to freeze momentarily while they are reloaded (as you said above). Small time, each time, but does add up.

So yeah, an optimization I'd love to see also, when time permits. :)

Keep up the good work!

**Comment by uggrock** [comment] 2017-05-22 16:11
The flickering is more or less by design in the list and grid perspective. In the photoswipe perspective there is no flickering. The file selection reflecting the currently opened files is meanwhile implemented.

**Closed by uggrock** 2017-05-22 16:11 UTC
