### ISSUE TITLE
Keyboard focus in HTML editor

### ISSUE THREAD

**Issue by pellenys** [tagspaces/tagspaces#199] opened 2015-02-02 12:56 UTC
Hi. I'm loving TagSpaces but have a bug to report.

If I'm using the HTML editor and either click on the Unordered List toolbar button, or press the Ctrl-Shift-7 shortcut, the focus moves out of the editing box.

The workaround is to click back into the editor after toggling the toolbar button, but that removes the speed benefit of the keyboard shortcut: hand to mouse, hand back to keyboard etc.

I'm using the Windows app, x64, on Win8.1.

Cheers,
Trystan

**Comment by uggrock** [comment] 2015-02-02 21:04
I could not reproduce the issue on Ubuntu Linux, I will try to reproduce it on Windows.

**Comment by uggrock** [comment] 2017-05-22 16:16
Issue will be closed as not reproducible.

**Closed by uggrock** 2017-05-22 16:16 UTC
