### ISSUE TITLE
TagSpaces does not show tags correctly 

### ISSUE THREAD

**Issue by papci0** [tagspaces/tagspaces#582] opened 2017-04-24 09:30 UTC
Hello,

in the version 2.8 Pro there seems to be issue with adding tags in the file manager. I use sidecar files for tags. If I add new tag to a file all already existing tags will be deleted and only the new one is saved in the sidecar file.  In the version 2.7 the tagging worked correctly. 

I use Ubuntu 17.04 64bit

**Comment by uggrock** [comment] 2017-04-24 09:56
Hello,

we were not able to reproduce this issue, can you please share with us some more details about the reproduction steps?

regards,
Ilian

**Comment by papci0** [comment] 2017-04-24 12:13
OK. Will try...

With version 2.7 installed I created some files and tagged them (screenshots with v27 in the names). Here I  can add and remove tags and I works as I expect.
After the upgrade to 2.8 I add a tag named tagn1 to a file (TEST2.txt) and what happens you can see on the screenshots with v28 in the name.
Additionally  I attached a start screenshot of tagspaces in debug modus.

regards
gregor

![sidecar_v28](https://cloud.githubusercontent.com/assets/9898793/25336509/1f310258-28f8-11e7-8d6e-82c2a1935a10.gif)
![sidecar_v27](https://cloud.githubusercontent.com/assets/9898793/25336505/1f2ba574-28f8-11e7-98f2-42999e845f81.gif)
![filemanager_v28](https://cloud.githubusercontent.com/assets/9898793/25336508/1f30790a-28f8-11e7-847f-331ecb65227c.gif)
![filemanager_v27](https://cloud.githubusercontent.com/assets/9898793/25336507/1f2cb5a4-28f8-11e7-92fe-584571115661.gif)
![debug_v28](https://cloud.githubusercontent.com/assets/9898793/25336506/1f2c8458-28f8-11e7-89de-d16708f630bb.gif)

**Comment by aejolene** [comment] 2017-06-28 14:46
Hello! I'm having the same issue in Windows, TagSpaces Pro v 2.8.0. When I drag a new tag to an already-tagged file it deletes the pre-existing tags from the JSON file.

**Comment by hugopeek** [comment] 2017-07-09 08:33
Same for me.. The tags also disappear after adding a new one, and only the newly assigned tag is shown on refresh. I checked the JSON file, and also there it's only the latest one..

![tagspaces-tag-issue](https://user-images.githubusercontent.com/5436121/27992313-3678eb8a-64c4-11e7-998d-8300e2fd94e1.gif)

I'm using TS Pro v2.8.0 on Linux Mint 18.1.

**Comment by uggrock** [comment] 2017-07-09 08:43
We are working on a fix it will be released soon.

**Comment by uggrock** [comment] 2017-07-09 14:54
fixed for versions 2.8.3 and 2.9

**Closed by uggrock** 2017-07-09 14:54 UTC
