### ISSUE TITLE
Drag and Drop causes crash in Linux

### ISSUE THREAD

**Issue by jrtokarz** [tagspaces/tagspaces#408] opened 2016-03-14 14:29 UTC
OS: Debian 8
DE: KDE Plasma 5
Kernel: 4.3.0
Tagspaces: 2.1.1

When dragging a file from Dolphin (KDE file manager) to Tagspaces, causes the application to crash even before the mouse button is released.

Running from the terminal produces the following output:

$ tagspaces 
[13898:0314/152806:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
The program 'tagspaces' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAtom (invalid Atom parameter)'.
  (Details: serial 420 error_code 5 request_code 20 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Failed to tell parent about crash.

**Comment by uggrock** [comment] 2016-03-23 14:31
Can you please try to reproduce the issue with version 2.1.4 from https://github.com/tagspaces/tagspaces/releases/tag/v2.1.4

**Comment by jrtokarz** [comment] 2016-03-23 15:18
In version v2.1.4, the application no longer crashes when a dragged file is dropped.  However, when the file is over the perspectives pane, the border of the pane changes to a blue dashed line but the file is not added to perspectives pane and it is not added to the tagged file location directory.

**Comment by uggrock** [comment] 2016-03-23 16:27
I will close this issue because the main problem is not reproducible anymore. I believe that your new issue is a refresh problem, which is already fixed for the next release.

**Closed by uggrock** 2016-03-23 16:27 UTC
