### ISSUE TITLE
No Thumbnails in Search Results

### ISSUE THREAD

**Issue by chobrah** [tagspaces/tagspaces#592] opened 2017-05-23 08:31 UTC
Thumbnails don't appear to show up for me in Grid view when viewing search results.  Thumbnails only appear to work when viewing all files in a folder.

I assume this is not the expected behaviour as I thought the point was to be able to view files based on an arbitrary tag based filtering.

I am using: TagSpaces Pro 2.8.0 - BuildID: 2.8.0.20170414113700  Windows 64bit.

Regards
Chris

**Comment by uggrock** [comment] 2017-05-23 08:52
Hi Chris,

thanks for reporting this, the issue is already fixed in version 2.8.2, so you can test it there if you wish. Since 2.8.2 is a pre-release there is no official 2.8.2 PRO release. Fixes made in pre-release will land in the next 2.9 release.

cheers,
Ilian

**Closed by uggrock** 2017-05-23 08:52 UTC
