### ISSUE TITLE
No Thumbnails in Windows 10

### ISSUE THREAD

**Issue by LyrithMelanctha** [tagspaces/tagspaces#842] opened 2019-01-15 20:59 UTC
I don't see thumbnails of any file in windos 10. I'm using TagSpaces 3.0.4
![tag1](https://user-images.githubusercontent.com/46727633/51209575-d548cd00-1910-11e9-8cff-2d66d8729277.PNG)

**Comment by uggrock** [comment] 2019-01-16 08:32
I am not able to reproduce this issue. Can you please check if you have a .ts folder on your desktop.

**Comment by LyrithMelanctha** [comment] 2019-01-16 18:05
No, I don´t have any .ts in my computer. This is what y see in the folder
![tags](https://user-images.githubusercontent.com/46727633/51269003-aa6a8180-19c1-11e9-9c25-5d0f07f71780.PNG)

**Comment by sone** [comment] 2019-06-20 11:16
How tagspaces thumbnails can be rebuilded? Is it a good idea e.g. to delete all ".ts" folders to make tagspaces rebuild the thumbnails?

I have also some directorys with ".ts" folders with already generated thumbnails by tagspaces but they are not visible in tagspaces. 
How can I find out why some jpgs preview is ok, some jpgs preview/thumbnail is not visible?

**Comment by jfml** [comment] 2020-05-03 13:13
I think I have the same Issue on Windows 10 with TagSpaces 3.5.2. Thumbnails/.ts-folders are not generated for a lot of folders. At first it seemed like only the main folder in a location would generate Thumbnails but I sometimes can trigger thumbnail generation for subfolders by repeadetly closing and reopening TagSpaces and then navigating to folders and sometimes the thumbnails get generated. 

I also noticed that when I start the program the „Loading or generating thumbnails“-message is displayed indefenitely until I do something (I tried just opening the program and waiting for half an hour but it did not go away). 

Can this have to do something with the Community VS Pro-Edition? I'm not really clear on what the differences are concerning thumbnails, I find this is worded kinda confusing in the website:

https://www.tagspaces.org/products/ (says thumbnails are not persistant in Community Edition)
https://www.tagspaces.org/products/pro/#thumbnailsGeneration (I read this as thumbnails are persistant in all Editions but Pro Edition has thumbnails for more filetypes?)

Are persistant thumbnails a Pro feature? Or is the pro feature that thumbnails are generated for more filetypes? I'm using the Community-Edition atm and to me it looks like the thumbnails that are being generated are persistent.

If I can supply more information/do more tests to solve this I'd be happy to (is there a way to generate logs?). I love TagSpaces but this problem makes it super hard to use.

**Comment by eholmes** [comment] 2020-07-16 13:27
I also have this problem even with the latest version, 3.5.4.  I do not see any .ts files in my photo folders.  My photos are on a network drive and I also see the 'loading or generating thumbnails' message.  Even when I set my location as a network folder with only 6 jpgs, the thumbnails never seem to finish generating.

**Comment by onejoule** [comment] 2020-12-24 17:41
I downloaded and installed Tagspaces 3.7.8 for the first time today on a freshly installed windows 10.
Generating thumbnails is not working correctly. It only shows the message "Loading or generating thumbnails". No information about what is happening and how long I should expect to wait. When selecting a file, a preview of another file is shown.
For many folders thumbnails doesn't show even after waiting several minutes. Now the program don't even let me select another folder to view. I had really high hopes after reading the presentation of this software.

It has to tell the user what it is doing, not just stop responding.

**Comment by uggrock** [comment] 2021-07-15 20:41
closing due to inactivity

**Closed by uggrock** 2021-07-15 20:41 UTC
