### ISSUE TITLE
v3.0.9 performances issues

### ISSUE THREAD

**Issue by gitdocke** [tagspaces/tagspaces#911] opened 2019-02-09 07:33 UTC
**Describe the bug**
Using Tagspaces v3.0.9 Pro
1- Changing among directories takes from 20 to 45 seconds depending which directory, before in V3.0.5 was 1 sec flat.
2- To apply a tag dragging it from the tag library and making it stick to the file takes at least 5 seconds, before in version 3.0.5 was around 1 second or less.
3- When preview a file, to open the viewer takes from 4 to 7 seconds, before was 1 second.
4- To resize the viewer dragging its border has a delay of around 3 seconds, before was instantly.

**Expected behavior**
To be as snappy as possible. Until a fix is found I go back to v3.0.5.

**Desktop (please complete the following information):**
 - OS: Debian 9 with KDE Plasma
 - Browser Firefox
 - Version 65.0

**Comment by gitdocke** [comment] 2019-02-10 02:32
I just tried v3.0.9 Pro in a machine with Windows 7; same problem than in Linux.
Also some additional quirks showed up, for example when changing directories the memory, in one of the 4 instances of TagSpaces.exe, jumped from 400MB to 900MB, to fall back to 400MB when I scrolled down till the end of this RAM hungry directory, and always showing delays of 30, 40 and even 50 seconds to display the new switched directory.
In Windows, another quirk was that the video crashed to a black screen with a big blinking underscore prompt on the upper left side corner of the screen , like it reverted to 640x480 mode. This happened just once.

**Comment by uggrock** [comment] 2019-02-10 09:10
This is very strange. I was not able to measure significant performance change on my machine in this version. I am testing currently with a directory containing 500 files, while every files having one tag in the filename and four in sidecar file, also 2500 tags... These files have also thumbnails, which are also loaded and displayed. The time needed on a Ubuntu with a core 7, 2,6 GHz is 3 sec.

**Comment by gitdocke** [comment] 2019-02-10 10:11
I have to mention that when I tried the Windows version, I copied the same directories containing the files and sidecars, so the same conditions were reproduced. 
Now I am trying the portable Linux version (3.0.9) and it has delays changing directories, but not so acute as the DEB one. Also the responsiveness to stick dragged tags is faster and the viewer opens almost as fast as v3.0.5.
Nevertheless, I will stick to old and dear v3.0.5, it works just fine for me.  
About the machine tested. It is a relatively old laptop with dual boot Linux/Windows. I add screenshots showing details.
![screenshot_20190210_042147](https://user-images.githubusercontent.com/22734449/52532328-10aca080-2cf1-11e9-9da7-e7014cca1935.png)
![screenshot_20190210_045733](https://user-images.githubusercontent.com/22734449/52532329-1bffcc00-2cf1-11e9-82f3-6f34de8247ed.png)
Thanks for your attention.

**Comment by uggrock** [comment] 2019-02-24 21:11
Can you please try our last 3.1.1 version and check if you still experience the performance issues.

**Comment by gitdocke** [comment] 2019-02-26 07:56
Using TagSpaces Pro 3.1.1 (Linux portable version), same machine as before.
I was testing this version last 3 or 4 days, there is some performance improvement compared to v3.0.9, but it is not great, however, I would say that this time it is "usable", at least for me and my patience.
Also I tested them side by side with v2.5.0 Pro, v2.8.0 Pro, and v2.9.0 Pro and the difference in perfomance against v3 is abysmal; nevertheless, versions 2 are acceptable in performance but very buggy and perhaps not ready for deployment in a production setting (IMHO of course).

------------------------
My test run for the current v3.1.1 was as follows:
The v3 Beta feature to scan for text have never been activated.
File's quantities and sizes declared do not include .ts folders content.

1- Starting the program and finishing to load the interface and default location = 11 secs. As shown in screenshot 1.

2- Double clicking on the Default Location at the "Location Manager" to display its content takes 45 secs. As shown in screenshot 2.

2a - Default location contains 14 main folders and some subfolders. Total tags 842.
**- Folder 1** ---> 134 files with 1.9GB /// clicking this directory to show its content takes 38 secs the first time, and all the following times 22 to 25 seconds (probably because is in RAM cache).
**- Folder 2** ---> 59 files with 204MB /// clicking this directory to show its content takes 10 secs the first time, and all the following times 5 seconds (probably because is in RAM cache). 
**- Folder 3** /// clicking this directory to show its content (3 folders) takes 7 secs the first time, and all the following times 3 seconds (probably because is in RAM cache).
----- Subfolder 1 ---> 1 file with 600KB /// NOT TESTED
----- Subfolder 2 ---> 30 files with 3GB /// NOT TESTED
----- Subfolder 3 ---> 4 files with 460MB /// NOT TESTED
**- Folder 4** ---> 5 files with 55MB /// NOT TESTED
**- Folder 5** ---> 8 files with 76MB /// NOT TESTED
**- Folder 6** ---> 122 files with 209MB /// NOT TESTED
**- Folder 7** ---> 20 files with 3MB /// NOT TESTED
**- Folder 8** ---> 10 files with 4MB /// NOT TESTED
**- Folder 9** ---> 28 files with 9MB /// NOT TESTED /// it contains NO TAGS
----- Subfolder 1 ---> 38 files with 482MB /// NOT TESTED /// it contains NO TAGS
----- Subfolder 2 ---> 13 files with 5MB /// NOT TESTED /// it contains NO TAGS
----- Subfolder 3 ---> 39 files with 21MB /// NOT TESTED /// it contains NO TAGS
----- Subfolder 4 ---> 14 files with 38MB /// NOT TESTED /// it contains NO TAGS
----- Subfolder 4 ---> 16 files with 3MB /// NOT TESTED /// it contains NO TAGS
----- Subfolder 6 ---> 678 files with 8.5GB /// NOT TESTED /// it contains NO TAGS
**- Folder 10** /// NOT TESTED /// it contains NO TAGS
----- Subfolder 1 ---> 46 files with 17MB /// NOT TESTED /// it contains NO TAGS
---------- Sub-subfolder 1 ---> 45 files with 905MB /// NOT TESTED /// it contains NO TAGS
---------- Sub-subfolder 2 ---> 8 files with 120MB /// NOT TESTED /// it contains NO TAGS
**- Folder 11** ---> 4 files with 31MB /// NOT TESTED
**- Folder 12** ---> 1 file with 128KB /// NOT TESTED
**- Folder 13** /// clicking this directory to show its content (2 folders) takes 16 secs.
----- Subfolder 1 ---> 2 files with 322MB /// clicking this directory to show its content takes from 2 to 3 secs.
----- Subfolder 2 ---> 92 files with 2.6GB /// clicking this directory to show its content takes from 30 to 38 secs.
**- Folder 14** ---> 2 files with 107KB /// NOT TESTED

![screenshot_20190226_005136](https://user-images.githubusercontent.com/22734449/53395740-9165d080-3970-11e9-9da9-b9a26a88f903.png)
![screenshot_20190226_011548](https://user-images.githubusercontent.com/22734449/53395747-96c31b00-3970-11e9-8b31-dca862ad3fff.png)

**Comment by gitdocke** [comment] 2019-02-26 19:31
I forgot to mention, the perfomance improvements noticed in v3.1.1 are mostly related to faster right click menus and applying tags.

**Comment by gitdocke** [comment] 2019-03-13 03:59
After uninstalling v3.1.1 Pro, I installed v3.0.5 Pro and works super fast, not so fast as v2.x but nevertheless it is pretty acceptable.
Before the time to open up Folder 13/Subfolder 2 was from 30 to 38 seconds, now is 2,5 seconds sharp!
I am keeping this version for sure.

![Screenshot_20190312_233118](https://user-images.githubusercontent.com/22734449/54252860-e2ee8d80-4522-11e9-879a-7386e2b1bb8a.png)

**Comment by uggrock** [comment] 2019-04-24 20:54
I am closing this issues, since the root cause #958 has been found.

**Closed by uggrock** 2019-04-24 20:54 UTC
