### ISSUE TITLE
Minor issue(s): unexpected filenames / tags

### ISSUE THREAD

**Issue by PythonAmateur742** [tagspaces/tagspaces#275] opened 2015-05-26 11:26 UTC
Just for the fun of it, I decided to mess a bit with the tag names. 

Scenario 1: Nested
Filename: [example1 [example2 example3]].txt
Resulting Tags: example1, [example2, example3
Resulting title: Empty
Conculsion: unexpected, apparently the nested closing bracket is recognized as code, while the nested opening tag wasn't.
Possible solution: replace every weird symbol between the first and the last bracket by nothing.

Scenario 2: double tags
Filename: [example1][example2].txt
Resulting tags: example1
Resulting title: Empty
Conclusion: Expected result, since the recognition of tags would probably stop after the closing bracket.
Possible solution: Repeat the code to see if there are more tags and add them, or add everything after the closing tag as title.

Scenario 3: Double tags with title at the end
Filename: [example1][example2] - Copy.txt
Resulting tags: example1
Resulting title: - Copy
Conclusion: Unexpected result. Scenario 2 already showed that no tags would be recognized, therefore I expected no other elements to be added as well. 
Possible solution: No solution needed.

Scenario 4: Title then nested tags then title again
Filename: this is a [example1][example2] - Copy.txt
Resulting tags: example1
Resulting title: this is a - Copy
Conclusion: Unexpected result. There is an omitted space in the title.
Possible solution: No solution needed, although this could lead to funny titles.

Scenario 5: Title with a lot of spaces and a tag
Filename: one two  three   four    five     [tag].txt
Resulting tags: tag
Resulting title: one two three four five
Conclusion: After scenario 4 an expected result
Possible solution: Don't omit spaces. In the limit of 255 chars spaces should not be hidden from users. Otherwise they don't know they have to fix the title.

**Comment by BasEbeling** [comment] 2015-05-27 07:57
I noticed in tagutils.js that the function `extractTitle()` uses this:
`var beginTagContainer = fileName.indexOf(BEGIN_TAG_CONTAINER);`
I think it should be the same as in the function `extractFileNameWithoutExt()`

I think the unexpected behaviour is caused by this difference.

**Comment by BasEbeling** [comment] 2015-05-31 15:37
I've added some code to my local installation, but I haven't reviewed it and tidied it up yet. I replaced the extractTags function. I haven't made a pull request for it, because this function is useless without extracting the title in a different way. But this code is functional, it will allow very dirty syntax:
```
  function extractTags(filePath) {
    var fileName = extractFileName(filePath);
	//var fileName = 't[te[tes[t est]t]st]est[[][]]][]]]'; // replaces the input filepath for testing purposes
	var beginTagContainer = fileName.indexOf(BEGIN_TAG_CONTAINER);
    var endTagContainer = fileName.indexOf(END_TAG_CONTAINER);
    var tagList = fileName.match(/\[|\]/g);
    if( tagList != null){
	var tagCount = fileName.match(/\[|\]/g).length; //script crashes on the regex... why?
	}
    var currentTagID = 0;
    var lastTagID = 0;
    var tagSetter = [];
    var tagCouples = [];
    var tagCoupleOpen = 0;
    var tagCoupleClose = 0;
    var singleCouples = [];
    var openCount = 0;
    var outerTags = [];
    var cleanedTags = [];
	var stringContainer = '';
	var tagContainer = [];
	var cleanedTags = [];
    var nested = false;
    //detect the valid tags
    for (i = 0; i < tagCount; i++) {
      /**	covered cases
1. [[]		multiple open, not enough closing
2. ][		  closing before opening
3. []		  open and close, wanted scenario
4. [][]	  multiple wanted scenario
5. []]		open, but close too many
6. [[]]	  nested tags, considered all as tags. Or: [parent [tags] children][second parent [tags] children]
**/
      var tagCouplesClone = {};
      if (tagList[i] === BEGIN_TAG_CONTAINER) {
        openCount++;
        currentTagID = fileName.indexOf(BEGIN_TAG_CONTAINER, lastTagID) + 1;
        tagSetter.push(currentTagID);
      } else if (tagList[i] === END_TAG_CONTAINER) {
        //if tagOpenCloseCount decreases a closing tag has been used. remove the last two from the tagSetter array. Push closing tag and pop twice to a new array.
        if (openCount > 0) {
          currentTagID = fileName.indexOf(END_TAG_CONTAINER, lastTagID + 1);
          openCount--;
          tagSetter.push(currentTagID);
          tagCoupleClose = tagSetter.pop();
          tagCoupleOpen = tagSetter.pop();
          singleCouples.push(tagCoupleOpen, tagCoupleClose);
        }
      }
      lastTagID = currentTagID;
    }
    //singleCouples.reverse();
    for (i = 0; i < singleCouples.length; i += 2) {
      //console.info(singleCouples[i]);
      nested = true;
      if (singleCouples[i] > singleCouples[i + 2] & singleCouples[i + 1] <
        singleCouples[i + 3]) {
        nested = true;
      } else {
        nested = false;
      }
      if (nested === false) {
        outerTags.push(singleCouples[i], singleCouples[i + 1]);
      }
    }
  for (i=0; i < outerTags.length; i += 2){
    stringContainer = fileName.slice(outerTags[i],outerTags[i+1]);
    if(stringContainer != ""){
	stringContainer = stringContainer.split(/\[|\]| /);
		for(i=0;i<stringContainer.length;i++){
			if(stringContainer[i].length > 0){
				tagContainer.push(stringContainer[i]);
			}
		}
    }
  }
```

**Comment by uggrock** [comment] 2020-12-04 23:25
@mladensap can you please create some unit test for the cases from this issue -> closing

**Closed by uggrock** 2020-12-04 23:25 UTC
