### ISSUE TITLE
Can't seem to assign a Key Binding

### ISSUE THREAD

**Issue by artman009** [tagspaces/tagspaces#532] opened 2017-01-04 23:31 UTC
My apologizes if this has been addresses elsewhere or if I am doing something obviously wrong but I cannot seem to assign a key binding to a tag.

I create a tag, edit it then attempt to setup a key binding (example: " ctrl+shift+8 ") but no matter what I type, it just says "Please match the requested format" in red. See image attachment [here](http://imgur.com/a/LLHGZ).

Am I doing something wrong?

**Comment by Gaston99** [comment] 2017-01-08 08:50
I had this issue too. Editing tags seems to be a bit buggy. I was going to log a separate report about this. It looks like you can only edit 1 thing per tag. If you notice when you edit a tag, if you want to add a key binding (for example 'ctrl+j'), when you type in the 'c', it's absolutely fine, when you type in the 't', it gives you the error. It appears that after every addition of a letter, it goes and checks something to make sure it's valid. This check effectively bugs out and you just constantly get the error.

The way around it is this:
You can only edit 1 tag at a time.
After every tag edit, you have to Reload the application (Ctrl + R)
Put the key bindings you want into a text editor and copy the whole binding, so in the example above, I'd have 'ctrl+j' (without the quotes) in my clipboard.
Edit the tag and paste the text into the key binding.
Don't try to change anything else, colour, tag text, etc or it will bug out.
Just Save
Then Reload the application.
Repeat for as many tags as you need to.
--------------
It is a bit of a pain, but once you're set up, it should be fine.

I can confirm that the above method worked for me.

**Comment by artman009** [comment] 2017-01-09 20:55
Ah, thanks. Yeah, this work-around works. Hopefully it'll be fixed soon.

Thanks! Much appreciated.

**Comment by uggrock** [comment] 2017-01-09 21:00
It will be fixed for the next release.

**Comment by uggrock** [comment] 2017-01-12 13:30
fixed for 2.7

**Closed by uggrock** 2017-01-12 13:30 UTC
Labels: bug
