### ISSUE TITLE
Tagspaces helper brings machine to its knees

### ISSUE THREAD

**Issue by sprig** [tagspaces/tagspaces#473] opened 2016-08-11 13:24 UTC
Hello,

I'm using TS Pro on a macbook (not pro). If I enable "show subfolder content" on a large folder (with a setting to show max 100 files), the computer becomes unusable. It appears that this is due to the indexing and thumbnail creation done by the helper.

It would be helpful if the helper was scheduled under a higher nice (man nice) level so as to disturb less the performance of the rest of the system.

Furthermore, I suggest that once a user adds a "location" to tagspaces, that the helper should automatically run in the background and index the files, and not just at the moment a user tries to look at a certain directory.

**Comment by sone** [comment] 2016-08-12 11:07
Hello, I can confirm this issue. I'm just starting to get used to TS Pro on both Windows 7 and Ubuntu 16.04 and TS Pro 2.4 is not useable because of this issue described by sprig above.

**Comment by uggrock** [comment] 2016-08-13 13:53
We will investigate this issue, for me it looks like that TSPro is starting to create the thumbnails disrespecting the file list size limitation.

**Comment by sprig** [comment] 2016-08-13 14:15
This is definitely not what is happening - I count the number of files in the .ts folders, and they do not increase much, and definitely not by more than the number of visible files.


This is actually a different issue that I meant to file - on one of my machines (the one that gets slowed down a lot) if I make TS list subfolders, the helper creates the appropriate thumbnails and indexes, whereas on another one it creates them only for files directly in the current folder.




On Sat, Aug 13, 2016 at 4:54 PM +0300, "Ilian" <notifications@github.com> wrote:












We will investigate this issue, for me it looks like that TSPro is starting to create the thumbnails disrespecting the file list size limitation.

**Comment by rdoila** [comment] 2016-12-14 13:46
Same here....
I purchased the Pro version few days ago for managing pdf and ebooks. Even when re-opening the same folder where thumbnails already exist, the application saturates the all memory (~12GB!) and system starts to swap.
A lot of IO is happening in the background by this app prior memory starts to be swapped.
Smells like a memory leak....
![capture](https://cloud.githubusercontent.com/assets/24320345/21184269/038f39c8-c20c-11e6-8d77-c276f697d758.JPG)

**Comment by uggrock** [comment] 2019-10-21 16:06
not relevant for version 3 -> closing

**Closed by uggrock** 2019-10-21 16:06 UTC
