### ISSUE TITLE
Not function at all with files inside Onedrive

### ISSUE THREAD

**Issue by HaimingZ** [tagspaces/tagspaces#667] opened 2018-02-03 10:36 UTC
Hello, 
I am using tagspaces 2.9.0 on Window10. The problem is: 
Tagspaces recognises  **every file** inside Onedrive folder as a **folder**. Including *pdf*, *docx*, *md*, *txt*, etc. The files have been saved on local drive. 
Files outside Onedrive folder do not come across this problem.
Please fix this.
Thank you.

**Comment by uggrock** [comment] 2018-02-04 13:23
Hello, 
and thanks for reporting. You are not the first user complaining about this issue, unfortunately we are not able to reproduce it on our testing Windows computer. It just works with OneDrive.... Are you using the Business Onedrive version?

**Comment by HaimingZ** [comment] 2018-02-07 08:49
Hello,
Thank you for a quick reply. To be clear, I am not using Business Ondrive version. 
I apologize that I can not use my office desktop (where the issue happens) right now because I am at home for Chinese new year vacation. So I can not give you more information on this issue for the time being. 
I test it again on my laptop (windows 10, tagspaces2.9.0, Onedrive standard version), and it turns out that Tagspaces works just fine. I have no idea if there is something wrong with my office desktop. If l can find something important, I will let you know.
Thanks again.
I love your software.

**Comment by HaimingZ** [comment] 2018-02-25 07:46
![image](https://user-images.githubusercontent.com/33821265/36639221-eec8c80c-1a42-11e8-9490-69407115e706.png)

Here is the screenshot.

**Comment by tiger940310** [comment] 2018-03-07 19:09
I'm having the same issue. For some reason it won't read the files in my One Drive. I am not using One Drive Business

**Comment by HaimingZ** [comment] 2018-03-15 06:14
Hello,
I just updated my windows system to 1803 (insider preview) a few days ago. The issue mentioned above disappeared. I don't know what's going on. Maybe the issue was caused by windows/onedrive.
 
![snipaste_2018-03-15_14-02-43](https://user-images.githubusercontent.com/33821265/37446804-b977b440-2859-11e8-9c8d-0bbb71ad7b0f.PNG)

**Comment by uggrock** [comment] 2018-03-27 20:39
Can you please try to disable the "Files On-Demand" feature in OneDrive and try to reproduce the issue?

**Comment by HaimingZ** [comment] 2018-03-28 02:26
I just disabled "Files On-Demand", but could not reproduce the issue. I think it has nothing to do with this feature.

**Comment by mbakstars** [comment] 2018-04-13 17:46
I am sorry to comment on a closed issue but wanted to let you know. I am having this issue with my onedrive personal, but not business (edu). As soon as I turned off "files on demand" on my personal, the program recognized the files and loaded correctly. W10E 64, 32bit TSP

**Comment by mbakstars** [comment] 2018-04-13 17:49
Save these files here in yellow
![image](https://user-images.githubusercontent.com/31328113/38750003-fb7b79c8-3eff-11e8-9521-1d3770defd3f.png)

**Comment by changhenry2** [comment] 2018-04-16 10:29
Same problem here.
On Onedrive standard version and Windows 10 64bit Redstone 3 (latest stable version)
Turning on and off "files on demand" does not help.
However, some very recent files (which I just modified about an hour ago) can be recognized by Tagspaces, all the others are recognized as directories.
I kind of believe the problem is related to the"files on demand" feature. 
Please help figuring this out, thanks a lot.

**Comment by changhenry2** [comment] 2018-04-17 14:17
Hi, I think I've figure it out.
For the files in Onedrive which cannot correctly shown in Tagspaces, the file attribute was set to "reparse point" (something like symbolic link, I don't know much about it either).
To have these files show in Tagspaces, you have to remove the reparse point attribute.
After several hours of researching, there seems no easy way of doing it.
Finally I used fsutil to remove it.
my powershell script:
Get-ChildItem "_path_name_" -Recurse -Include *.* | ForEach { fsutil reparsepoint delete $_ } 
and after this all files in _path_name_ will not have the reparse point attribute.

**Comment by uggrock** [comment] 2018-04-18 09:02
Hi @changhenry2 ,
and thanks for digging this out. It appears that the real issue is here: https://github.com/nodejs/node/issues/12737

kind regards,
Ilian

**Comment by uggrock** [comment] 2021-07-15 20:48
not reproducible anymore -> closing

**Closed by uggrock** 2021-07-15 20:48 UTC
